name: Deploy Database

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  call-db-workflow:
    uses: wander-suite/wander-devops/.github/workflows/db-publish-workflow.yml@main
